name: master_thesis
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.9
  - openai
  - scikit-learn
  - pytorch=1.8.1
  #- cudatoolkit=11.1
  - tiktoken
  - pip
  - pip:
    - transformers
    - sentencepiece
    - pandas
